name: sql_records
description: A minimal, functional wrapper for SQL databases using Dart 3 records.
version: 0.4.0
repository: https://github.com/aleclarson/sql_records

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  powersync: ^1.17.0
  sqlite3: ^2.9.4
  sqlite_async: ^0.13.1
  postgres: ^3.1.2
  meta: ^1.11.0

dev_dependencies:
  test: ^1.24.0
