name: sqlite_records
description: A minimal, functional wrapper for SQLite/PowerSync using Dart 3 records.
version: 0.1.0
repository: https://github.com/aleclarson/sqlite_records

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  powersync: ^1.17.0
  sqlite3: ^2.9.4
  sqlite_async: ^0.13.1

dev_dependencies:
  test: ^1.24.0
